[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "x10tt"
authors = [{name = "Marius Steinbach", email = "m@steinbach.io"}]
dynamic = ["version", "description"]
